UUID : '0000f22e-0000-1000-8000-00805f9b34fb'
START_TIME : ['01:15:01', '01:15:13', '01:15:24', '01:15:36', '01:15:46', '01:15:54', '01:16:04', '01:16:13']
END_TIME : ['01:15:05', '01:15:17', '01:15:28', '01:15:40', '01:15:50', '01:15:58', '01:16:08', '01:16:17']
LABEL_LIST : [0, 1, 2, 3, 4, 5, 6, 7]
# START_TIME : ['01:16:13', '01:16:04', '01:15:54', '01:15:46', '01:15:36', '01:15:24', '01:15:13', '01:15:01']
# END_TIME : ['01:16:17', '01:16:08', '01:15:58', '01:15:50', '01:15:40', '01:15:28', '01:15:17', '01:15:05']
# LABEL_LIST : [7, 6, 5, 4, 3, 2, 1, 0]
BEFORE_DIR : './before/U19e_outdoor1201/'
AFTER_DIR : './after/U19e_outdoor1201test1/'
OUTPUT_DIR: 'output'
FILE : 'sniffer_'
FILE_TYPE : 'csv'
OUTPUT_NAME : 'U19e_outdoor1201test1'
AP_NUMS : 6
AP_NAME : ['zero', 'one', 'two', 'three', 'four', 'five']
TEST_FOR_VIDEO : false
TEST_VIDEO_PATH : './videos/1201test1.mp4'

MODEL :
  TYPE : '1DCNN'
  INIT_WEIGHTS : true
  #PRETRAINED : ''
  #PRETRAINED : 'output/U19e_outdoor0103/checkpoint.pth'
  PRETRAINED : 'output/U19e_outdoor1201/checkpoint_1dcnn_t1.pth'
  #PRETRAINED : 'output/sharp4025_test2/checkpoint.pth'

TRAIN :
  BATCH_SIZE : 32
  SHUFFLE : true
  BEGIN_EPOCH : 0
  END_EPOCH : 200
  OPTIMIZER : adam
  LR : 0.001
  LR_FACTOR : 0.1

TEST :
  #RSSI_LIST : [ [-42, -103], [-54, -96], [-55, -99], [-59, -96]] # U19e
  #RSSI_LIST : [ [-48, -103], [-52, -95], [-30, -97], [-48, -91]] # Sharp
  #RSSI_LIST : [ [-38, -96], [-31, -93], [-26, -93], [-29, -97]] # U19e outdoor1
  #RSSI_LIST : [ [-44, -95], [-28, -101], [-11, -97], [-28, -96]] # U19e outdoor2
  RSSI_LIST : [[-41, -98], [-30, -102], [-28, -101], [-28, -96], [-30, -98], [-33, -95]] # U19e outdoor3

